project_id = "jphwiytvplntnkcbivpu"

[functions.process-invoice]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.create-planner]
verify_jwt = false
